db:
  main:
    database: 'yadas-go'
    host: 'aa1i22z0m9xdw6t.c6duqy4zfndg.us-east-2.rds.amazonaws.com'
    username: 'devPostgres'
    password: '!XT<`u^6mc'
    port: 5432
    synchronize: true
    ssl: false
  
jwt:
  secret: 'yadas-test-secret'