db:
  main:
    database: '${RDS_DB_NAME}'
    host: '${RDS_HOSTNAME}'
    username: '${RDS_USERNAME}'
    password: '${RDS_PASSWORD}'
    port: 5432
    synchronize: true
    ssl: false
  
jwt:
  secret: 'yadas-test-secret'