db:
  main:
    database: 'yadas-go'
    host: 'localhost'
    username: 'developmentPostgres'
    password: '!XT<`u^6mc'
    port: 5432
    synchronize: true
    ssl: false
  
jwt:
  secret: 'yadas-test-secret'