db:
  main:
    database: 'yadas-go'
    host: 'aanzhesh2v2wc.c6duqy4zfndg.us-east-2.rds.amazonaws.com:5432'
    username: 'devPostgres'
    password: '!XT<`u^6mc'
    port: 5432
    synchronize: true
    ssl: false
  
jwt:
  secret: 'yadas-test-secret'