db:
  main:
    database: 'postgres'
    host: 'aa17jzyp3rk2jwe.c6duqy4zfndg.us-east-2.rds.amazonaws.com'
    username: 'postgres'
    password: 'Yadas2020'
    port: 5432
    synchronize: true
    ssl: false

jwt:
  secret: 'yadas'
  